### ISSUE TITLE
Acoustics Enrichment not completed 

### ISSUE THREAD

**Issue by staceyharkin** [MontrealCorpusTools/ISCAN#133]
In ISCAN Tutorial 1 - Sibilants, the acoustics enrichment using sibilant_jane_optimized.praat would not complete after running for 20 minutes while I added the other enrichments and waited. I then reset and re-ran it and waited for almost 10 minutes. Then I checked the download in a notepad, remade the enrichment, and it has now been running for around 10 minutes again without completing. 

This is with Chrome on an admittedly slow university computer, but all of the other ones completed in under a minute.
 
![image](https://user-images.githubusercontent.com/42970736/45041401-20e49380-b060-11e8-83fd-a9b3224f9146.png)

**Comment by mmcauliffe** [comment]
This has been fixed.

**Comment by vannawillerton** [comment]
I know this was previously fixed, but I seem to  be having the same issue in testing **Hastings** now. All other enrichments work. 

I tried deleting and redoing the enrichment, same problem. The chrome console thing doesn't seem to show any activity even though the table shows that the enrichment is 'running'.
