### ISSUE TITLE
More robust error message when neo4j or influxdb do not start properly

### ISSUE THREAD

**Issue by MichaelGoodale** [MontrealCorpusTools/ISCAN#180]
Currently neo4j will crash if the port is blocked(presumably it could also crash for other reasons). It would probably be helpful to forward any error messages from neo4j or influxdb to ISCAN so that people can know any issues with starting the database and fix them themselves.

**Comment by mmcauliffe** [comment]
Ok, I've added a check to whether ports are open before starting and will raise an exception now if they're not.

**Comment by msonderegger** [comment]
Thanks!

On Mon, Feb 4, 2019 at 2:22 PM Michael McAuliffe <notifications@github.com<mailto:notifications@github.com>> wrote:

Closed #180<https://github.com/MontrealCorpusTools/ISCAN/issues/180>.
