### ISSUE TITLE
Memory error when encoding syllables/utterances

### ISSUE THREAD

**Issue by james-tanner** [MontrealCorpusTools/ISCAN#184]
I'm getting the following error
`neobolt.exceptions.TransientError: There is not enough memory to perform the current task.`
when trying to encode encode utterance for Switchboard, and for syllables on SOTC. This is distinct from the previous error happening during corpus import.

**Comment by mmcauliffe** [comment]
@james-tanner I think this is all resolved now, right?  Both Switchboard and SOTC have been enriched with syllables/utterances successfully?
