### ISSUE TITLE
Token level enrichment

### ISSUE THREAD

**Issue by mmcauliffe** [MontrealCorpusTools/ISCAN#193]
It should be possible to import token properties via a CSV.  The workflow imagined is:

1. Generate query matching specific conditions (i.e., all sibilants)
2. Export CSV with information for further processing
3. Run a script that adds column information or creates a new CSV with relevant idenfiers
4. Upload new CSV back to ISCAN and enrich tokens with new properties

For this to be possible, the following steps have to be done:

- [x] Token ID information in query needs to be exportable
- [x] Token enrichment UI needs to be created
- [x] Token enrichment functionality has to be added to the Enrichment model

In addition, new functionality has to be written in PolyglotDB (see https://github.com/MontrealCorpusTools/PolyglotDB/issues/131).

**Comment by msonderegger** [comment]
whoa cool, steps are now possible..
