### ISSUE TITLE
User with subset of corpus permissions unable to Query corpus

### ISSUE THREAD

**Issue by vannawillerton** [MontrealCorpusTools/ISCAN#206]
When a user has access to a corpus with only the 'Can enrich' and 'Can access database' permissions (i.e. the permissions in django we want to give for any restricted corpora), Enrichments all work fine, but Queries never complete. The user gets stuck waiting for query results. 

The user is apparently unauthorized to see the query results. This is a permissions issue (we know because super-users can see the query results that the restricted user cannot).

**Comment by mmcauliffe** [comment]
I believe this should be fixed now with the permissions update, but can you test it again Vanna?
