### ISSUE TITLE
Unable to select classifier for VOT enrichment

### ISSUE THREAD

**Issue by james-tanner** [MontrealCorpusTools/ISCAN#207]
The selection of a custom AutoVOT classifier for VOT enrichment appears broken on my browser. Selecting one of the default presets works fine, but other combinations result in an unrunnable enrichment.
![image](https://user-images.githubusercontent.com/8843358/58639189-75056700-82c4-11e9-853b-9897ec2be93e.png)
Browser version:
Google Chrome Version 74.0.3729.169 on MacOS 10.12.4

**Comment by msonderegger** [comment]
@MichaelGoodale @james-tanner did this get addressed?

**Comment by MichaelGoodale** [comment]
@msonderegger  just fixed it. Something weird that only popped up in chrome so I hadn't ever seen it before.
