### ISSUE TITLE
Make viewable subannotations "stick"

### ISSUE THREAD

**Issue by MichaelGoodale** [MontrealCorpusTools/ISCAN#211]
currently once you start looking at VOTs in the detail viewer, you have to reselect them each time you go to the next phone. It would be nice to be able to keep it activated at all times (unless deactivated).

**Comment by james-tanner** [comment]
I think the default should be: subannotations on and the VOT selected, so you can immediately see the blue selection across both the wave and the spectrogram. Right now it's a bit difficult to see what part of the spectrogram has been selected by autoVOT.
