### ISSUE TITLE
AudioBNC fails to import in ISCAN

### ISSUE THREAD

**Issue by vannawillerton** [MontrealCorpusTools/ISCAN#221]
Last tested May 2019. AudioBNC fails to import in ISCAN. The cause is currently unknown.

**Comment by MichaelGoodale** [comment]
This was fixed recently on the corpus itself by running a script which removed empty TextGrids. Furthermore, with [this commit](https://github.com/MontrealCorpusTools/PolyglotDB/commit/b6a7955d27c864b94a6f32b6d70ee0ce34e3dc44), the root problem (empty TextGrids causing errors) has been fixed as these TextGrids are now skipped.

**Comment by msonderegger** [comment]
Awesome!  @vannawillerton so now AudioBNC (the @MichaelGoodale version) does import?
