### ISSUE TITLE
Datasets using DISC transcriptions should not select 'stressed vowels' subset

### ISSUE THREAD

**Issue by vannawillerton** [MontrealCorpusTools/ISCAN#223]
ISCAN incorrectly selects a 'stressed vowels' subset in the 'phone subset' enrichment for datasets using DISC transcriptions which **do not** distinguish stressed vowels:

![Screenshot from 2019-06-17 12-30-45](https://user-images.githubusercontent.com/35343316/59621171-b38c8580-90fc-11e9-95f0-715e689cb9e8.png)

Ideally this page would look like it does for Buckeye and would not allow a selection of stressed vowels:

![Screenshot from 2019-06-17 12-38-35](https://user-images.githubusercontent.com/35343316/59621246-df0f7000-90fc-11e9-8af5-5136c562a734.png)

The datasets we have which use DISC transcriptions are **SOTC, GlasgowBiD & Glaswasian**

**Comment by vannawillerton** [comment]
Additionally, the 'syllabics' subset does not automatically select all the vowels, but a small subset. This should also be fixed.

**Comment by msonderegger** [comment]
Bizarre. @MichaelGoodale could you investigate/fix?

**Comment by MichaelGoodale** [comment]
So these default subsets weren't using the SPADE config files, but I'm in the process of updating them so that that's the case. From now on it'll use the spade config file, and if that config file is empty (e.g. no stressed vowels), that subset will be empty
