### ISSUE TITLE
Edinburgh corpus fails to import

### ISSUE THREAD

**Issue by vannawillerton** [MontrealCorpusTools/ISCAN#224]
This corpus has previously been imported successfully but appears not to work anymore. Cause unknown.

**Comment by msonderegger** [comment]
@MichaelGoodale could you investigate, consulting with @vannawillerton and @james-tanner as needed?

**Comment by MichaelGoodale** [comment]
Just keeping track of some observations as I figure stuff out with this corpus. 

- There's inconsistent capitalisation across files even though I think speakers are reading the same prompt, so that might be problematic for queries, maybe the entire corpus should just be switched to lower-case?
