### ISSUE TITLE
Hastings Formant points not properly encoded

### ISSUE THREAD

**Issue by vannawillerton** [MontrealCorpusTools/ISCAN#225]
When running tutorial 2 on the Hastings corpus in ISCAN, the formants appear to not get encoded properly. I can see this only when saving the CSV export file from my queries, the columns relating to the 'Refined Formant Points or Tracks' enrichment are empty (A1, A2, A3, B1, B2, B3, F1, F2, F3, and num_formants). This screenshot is from the ISCAN interface but I have generated a complete export file and confirmed that this is true for every phone.

![Screenshot from 2019-06-23 13-08-32](https://user-images.githubusercontent.com/35343316/59979661-7cb0e680-95b8-11e9-89f0-a104d7c1cbf2.png)

I have not seen this problem in export files from other corpora, so it appears to be specific to this dataset.

The enrichments all ran completely fine, including the relevant 'Refined Formant Points or Tracks' using the Raleigh vowel prototypes file.

**Comment by msonderegger** [comment]
@MichaelGoodale could you investigate, consulting with Vanna as needed?

**Comment by MichaelGoodale** [comment]
The issue comes from the fact that ISCAN isn't finding the audio files (even though it imports fine). This is because of the files ending in `.WAV` rather than `.wav`. I've made a new issue for this fix in the SPADE repo montrealcorpustools/SPADE#31

**Comment by MichaelGoodale** [comment]
This was fixed both in SPADE and with MontrealCorpusTools/PolyglotDB#150
